import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Dekujeme: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>PP Financial - Děkujeme</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        style={{ backgroundImage: `url(/api/dashboard/backgroundImg)`, backgroundPositionX: 'center' }}
        className={styles.main}
      >
        <div className={styles.mainCover} />
        <div className={styles.content}>
          <div className={styles.welcomeThank}>
            <h2 className={styles.welcomeText}>Děkujeme za vyplnění testu</h2>
            <h4 className={styles.welcomeText}>Do 48 hodin se na test podíváme a v případě úspěchu se ozveme</h4>
          </div>
          <div className={styles.thankYou}>
            <iframe
              style={{
                boxShadow: 'none',
                border: 'none',
              }}
              width='100%'
              height='100%'
              src='https://player.vimeo.com/video/624226239?autoplay=1'
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Dekujeme;
