import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Cookies from 'cookies';
import { axiosInstance } from '../../../code/constants';

import { Grid, Typography, Accordion, AccordionSummary, AccordionDetails } from '@mui/material';
import { getAnswers } from '../../../code/api';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import styles from '../../../styles/Home.module.css';
import { Create, Delete } from '@mui/icons-material';
import { format, parseISO } from 'date-fns';

const Dashboard: NextPage<{ answers: any[] }> = ({ answers }) => {
  console.log(answers);
  return (
    <>
      <Head>
        <title>PP Financial - Admin dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography>Odpovědi</Typography>
      <Grid marginTop={5}>
        {!answers || !(answers.length > 0) ? (
          <div>Zatím nemáte žádné Odpovědi</div>
        ) : (
          <div>
            {answers.map((answ) => (
              <Accordion key={answ._id}>
                <AccordionSummary expandIcon={<ExpandMoreIcon />} aria-controls='panel1a-content' id='panel1a-header'>
                  <Typography>{format(new Date(answ.createdAt), 'd.M.yyyy')}</Typography>
                </AccordionSummary>
                <AccordionDetails>
                  {answ.answers.map((content: string) => (
                    <Typography key={content}>{content}</Typography>
                  ))}
                </AccordionDetails>
              </Accordion>
            ))}
          </div>
        )}
      </Grid>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const cookies = new Cookies(req, res);

  const token = cookies.get('token');

  const { data } = await axiosInstance.get('/admin', { headers: { Authorization: `Bearer ${token}` } });

  if (!data) {
    return {
      redirect: {
        destination: '/admin',
        permanent: false,
      },
    };
  }

  try {
    const answersData = await getAnswers({ token: token! });
    const answers = answersData.data;
    return {
      props: {
        answers,
      },
    };
  } catch (error) {
    return {
      props: {},
    };
  }
};

export default Dashboard;
