import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Cookies from 'cookies';
import { axiosInstance } from '../../../code/constants';

import { Typography } from '@mui/material';

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>PP Financial - Admin dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography>Admin dashboard</Typography>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const cookies = new Cookies(req, res);

  const token = cookies.get('token');

  const { data } = await axiosInstance.get('/admin', { headers: { Authorization: `Bearer ${token}` } });

  if (!data) {
    return {
      redirect: {
        destination: '/admin',
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export default Dashboard;
